# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install --force
    - name: Set up Angular CLI
      run: npm install -g @angular/cli
    - name: Build
      run: ng build
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        name: FonkioNasViewerAngular
        path: dist/fonkio-nas-viewer-angular/
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download dist
      uses: actions/download-artifact@v2
      with:
        name: FonkioNasViewerAngular
        path: dist/fonkio-nas-viewer-angular/
    - name: Deploy dist
      run: |
        ls -al
        
